@startuml
class Order {
   order_nr
   email
   localDate
}

class User {
   email
   password
   balance
}

class Cupcake {
   topping
    bottom
    price
}

class Topping {
    name
    price
}

class Bottom {
   name
   price
}

User "1" --> "*" Order : places >
Order "1" --> "*" Cupcake : contains >
Cupcake "1" --> "1" Topping : has >
Cupcake "1" --> "1" Bottom : has >
@enduml
